// Country data mapping dial codes to flag emojis and names
const countryData: Record<string, { flag: string; name: string }> = {
  '91': { flag: '🇮🇳', name: 'INDIA' },
  '1': { flag: '🇺🇸', name: 'USA' },
  '44': { flag: '🇬🇧', name: 'UK' },
  '971': { flag: '🇦🇪', name: 'UAE' },
  '65': { flag: '🇸🇬', name: 'SINGAPORE' },
  '61': { flag: '🇦🇺', name: 'AUSTRALIA' },
  '49': { flag: '🇩🇪', name: 'GERMANY' },
  '33': { flag: '🇫🇷', name: 'FRANCE' },
  '81': { flag: '🇯🇵', name: 'JAPAN' },
  '86': { flag: '🇨🇳', name: 'CHINA' },
  '977': { flag: '🇳🇵', name: 'NEPAL' },
  '880': { flag: '🇧🇩', name: 'BANGLADESH' },
  '92': { flag: '🇵🇰', name: 'PAKISTAN' },
  '94': { flag: '🇱🇰', name: 'SRI LANKA' },
  '60': { flag: '🇲🇾', name: 'MALAYSIA' },
  '62': { flag: '🇮🇩', name: 'INDONESIA' },
  '63': { flag: '🇵🇭', name: 'PHILIPPINES' },
  '66': { flag: '🇹🇭', name: 'THAILAND' },
  '84': { flag: '🇻🇳', name: 'VIETNAM' },
  '82': { flag: '🇰🇷', name: 'SOUTH KOREA' },
  '7': { flag: '🇷🇺', name: 'RUSSIA' },
  '39': { flag: '🇮🇹', name: 'ITALY' },
  '34': { flag: '🇪🇸', name: 'SPAIN' },
  '31': { flag: '🇳🇱', name: 'NETHERLANDS' },
  '41': { flag: '🇨🇭', name: 'SWITZERLAND' },
  '43': { flag: '🇦🇹', name: 'AUSTRIA' },
  '32': { flag: '🇧🇪', name: 'BELGIUM' },
  '46': { flag: '🇸🇪', name: 'SWEDEN' },
  '47': { flag: '🇳🇴', name: 'NORWAY' },
  '45': { flag: '🇩🇰', name: 'DENMARK' },
  '358': { flag: '🇫🇮', name: 'FINLAND' },
  '48': { flag: '🇵🇱', name: 'POLAND' },
  '55': { flag: '🇧🇷', name: 'BRAZIL' },
  '52': { flag: '🇲🇽', name: 'MEXICO' },
  '54': { flag: '🇦🇷', name: 'ARGENTINA' },
  '57': { flag: '🇨🇴', name: 'COLOMBIA' },
  '56': { flag: '🇨🇱', name: 'CHILE' },
  '27': { flag: '🇿🇦', name: 'SOUTH AFRICA' },
  '20': { flag: '🇪🇬', name: 'EGYPT' },
  '234': { flag: '🇳🇬', name: 'NIGERIA' },
  '254': { flag: '🇰🇪', name: 'KENYA' },
  '966': { flag: '🇸🇦', name: 'SAUDI ARABIA' },
  '974': { flag: '🇶🇦', name: 'QATAR' },
  '968': { flag: '🇴🇲', name: 'OMAN' },
  '973': { flag: '🇧🇭', name: 'BAHRAIN' },
  '965': { flag: '🇰🇼', name: 'KUWAIT' },
  '964': { flag: '🇮🇶', name: 'IRAQ' },
  '98': { flag: '🇮🇷', name: 'IRAN' },
  '90': { flag: '🇹🇷', name: 'TURKEY' },
  '972': { flag: '🇮🇱', name: 'ISRAEL' },
  '353': { flag: '🇮🇪', name: 'IRELAND' },
  '64': { flag: '🇳🇿', name: 'NEW ZEALAND' },
  '852': { flag: '🇭🇰', name: 'HONG KONG' },
  '886': { flag: '🇹🇼', name: 'TAIWAN' },
  '960': { flag: '🇲🇻', name: 'MALDIVES' },
  '975': { flag: '🇧🇹', name: 'BHUTAN' },
  '95': { flag: '🇲🇲', name: 'MYANMAR' },
  '855': { flag: '🇰🇭', name: 'CAMBODIA' },
  '856': { flag: '🇱🇦', name: 'LAOS' },
};

export function getCountryInfo(dialCode: string | null | undefined): { flag: string; name: string } | null {
  if (!dialCode) return null;
  
  // Clean the dial code (remove + if present)
  const cleanCode = dialCode.replace(/^\+/, '').trim();
  
  return countryData[cleanCode] || null;
}
